### ISSUE TITLE
Trademark Violation

### ISSUE THREAD

**Issue by drhsqlite** [vapor/sqlite-kit#47]
Please do NOT use the name "SQLite" for your project.

"SQLite" is a registered trademark.  "SQLite" refers to the underlying database engine upon which you have built a wrapper.  By calling your project "SQLite", you are confusing people about what software they are running.  Using the name "SQLite" also implies that you are associated with the original SQLite project, which is dishonest.

You are welcomed to use "SQLite" as part of the name for your software, so that people know that it uses SQLite.  For example, you might call your software "SQLite Wrapper for Swift" or "Vapor's Swift SQLite Wrapper".  But you may not use the unqualified name "SQLite".

**Comment by joscdk** [comment]
@drhsqlite thanks for giving us notice of this, tbh. We was not aware of it. We will look into this asap :)

**Comment by tanner0101** [comment]
We will rename this package to `NIOSQLite` and move it to `vapor/nio-sqlite`. Does that sound good @drhsqlite?

**Comment by drhsqlite** [comment]
On 7/25/18, Tanner <notifications@github.com> wrote:
> We will rename this package to `NIOSQLite` and move it to
> `vapor/nio-sqlite`. Does that sound good @drhsqlite?
>

This is definitely an improvement.  Thanks.

To help avoid confusion, let me recommend some additional minor edits:

(1) Change the subtitle to "A Swift wrapper for SQLite" or "A Swift
wrapper around SQLite".  The existing title "SQLite wrapper for Swift"
makes it sound like your software is an add-on to SQLite that enables
SQLite to use Swift, while (if I understand correctly) the opposite is
true: your software is an library for Swift that allows Swift to use
with SQLite.

(2) In the README.md file, below the name, perhaps insert the same
subtitle "A Swift wrapper for SQLite".

The name change to "NIOSQLite" and the other two edits (or something
similar) will go a long way to helping busy programmings to quickly
grasp the distinction between your software and the canonical SQLite
library.  The less time developers spend thinking about such things,
the more time they have available to write their software, which is
the end goal of this whole exercise.

Thank you for your cooperation.

-- 
D. Richard Hipp
drh@sqlite.org

**Comment by tanner0101** [comment]
This package has been renamed to `SQLiteKit` in #52
