### ISSUE TITLE
Set table alias in raw query but result has original table name

### ISSUE THREAD

**Issue by t-ae** [vapor/sqlite-kit#48]
Sample repositopry.
https://github.com/t-ae/fluent-example/tree/sqlite-decoder-bug

I wrote the query that joins `persons` table two times in MySQL. It works well.
https://github.com/t-ae/fluent-example/blob/sqlite-decoder-bug/Tests/AppTests/AppTests.swift#L61-L113

In SQLite, however, the result `[SQLiteColumn: SQLiteData]` doesn't have alias but have original one.
Since same table is joined two times, there should be duplicated columns but it is not seen (maybe overriden?).
https://github.com/t-ae/fluent-example/blob/sqlite-decoder-bug/Tests/AppTests/AppTests.swift#L8-L59

In my example, `messages` table has 4 columns and `persons` table has 2 columns, so the result of query must have 8 columns.
In [this method](https://github.com/vapor/sqlite/blob/635ad49b2d6395b63462abffcce58ee38be1e4cc/Sources/SQLite/Database/SQLiteStatement.swift#L58-L71) column count is 8, but the returning `columns` has duplicate `table`/`name`.
<img width="256" alt="2018-08-23 10 49 22" src="https://user-images.githubusercontent.com/12446914/44500176-4bc70300-a6c2-11e8-9ffa-f4215c9dc5c2.png">

It uses `sqlite3_column_table_name` to get table name.
https://github.com/vapor/sqlite/blob/635ad49b2d6395b63462abffcce58ee38be1e4cc/Sources/SQLite/Database/SQLiteStatement.swift#L151
But documentation comment says:

> ** ^The names returned are the original un-aliased names of the
> ** database, table, and column.

**Comment by t-ae** [comment]
I don't know whether it is a bug or specification.
But I think it'll be good if `mysql`/`postgresql`/`sqlite` has same behavior :)

**Comment by mixio** [comment]
Created a example repository at : https://github.com/mixio/multi-join-test
