### ISSUE TITLE
[4.0.0-alpha.1.1] Issues when connecting to existing SQLite file....

### ISSUE THREAD

**Issue by markm77** [vapor/sqlite-kit#54]
I noticed two issues:

1. Need to use SQLRaw("json") for column names to access data.... e.g. 
```swift
                let firstFuture = Storage.shared.db.select()
                    .column(SQLRaw("json"))
                    .from("SoftwareStatements")
                    .where(SQLColumn(SQLRaw("id")), .equal, SQLBind(softwareStatementId))
                    .all()
```

2. Cannot access JSON data stored as text rather than 'blob' since attempt like
```swift
let result: SQLRow = returnedFromFuture
let softwareStatement = try! result.decode(column: "json", as: SoftwareStatement.self)
```
triggers this fatal error in ```SQLiteDataDecoder```
```
            guard case .blob(var buffer) = self.data else {
                fatalError()
            }
```
with no other way exposed to obtain the text read from the database....

Would be grateful if, in relation to (2), a method was exposed on ```SQLRow``` to access or decode SQLiteData of type text from database.

**Comment by markfinlabs** [comment]
Okay issue (1) is clearer once using DB Browser for SQLite to inspect DB Table schema (Create statement).

My database has:
```sql
CREATE TABLE "SoftwareStatements" ("id" TEXT PRIMARY KEY NOT NULL, "json" TEXT NOT NULL)
```

Whereas database created by SQLKitTests.swift (modified to create SQLite DB as file) has:
```sql
CREATE TABLE 'galaxies'('id' INTEGER PRIMARY KEY AUTOINCREMENT, 'name' TEXT)
```

Not sure which is best but this probably explains need for SQLRaw with my database.

**Comment by markfinlabs** [comment]
Okay issue (2) is worked around by performing decode in two steps.....

```swift
                var softwareStatementString: String = try result.decode(column: "json", as: String.self)
                var softwareStatement: SoftwareStatement = try Storage.shared.jsonDecoder.decode(
                    SoftwareStatement.self,
                    from: Data(softwareStatementString.utf8)
                )
```

If this is intended use, could I suggest maybe ```SQLRow.decode``` be renamed or documentation added to indicate this is more like a result read and user should perform their own decode afterwards?

NB: In relation to issue (1), thankfully no SQLRaw wrap required for ```"json"``` as only ```String``` column argument accepted by ```SQLRow.decode```. This is inconsistent though with column name input behaviour described in issue (1) so worth noting.
