### ISSUE TITLE
why does supportsAutoIncrement return false?

### ISSUE THREAD

**Issue by kojirou1994** [vapor/sqlite-kit#72]
https://github.com/vapor/sqlite-kit/blob/f0980810d474d092c86479c656cb50754c1e10c7/Sources/SQLiteKit/SQLiteDialect.swift#L38

**Comment by tanner0101** [comment]
> The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. It is usually not needed.

From: https://sqlite.org/autoinc.html

**Comment by kojirou1994** [comment]
Thank you, I get it
